#!/bin/sh

#Start with exercice 00
dir='source/00'

#Choose a random folder in 00
folder=`/bin/ls -d "$dir"/*/ | sort --random-sort | head -1` 

#Get only name of folder
newfolder=$( echo "$folder" | cut -d '/' -f3-)

#copy random folder
cp -r $folder subjects/$newfolder

#newfolder=$($folder | cut -d '/' -f3-)





#echo "The randomly-selected file is: $folder" && cut -d'/' -f3-
echo "The first exercie is: $newfolder"

#echo "$folder" | cut -d'/' -f3-

#nbfolder = ls | wc -l
#echo "nb $nbfolder as"

count=$(find ./subjects -maxdepth 1 -type d|wc -l)
let count=count-1
echo $count

