#!/bin/sh

#check progress
progress=`cat progress.txt`
exercice=`cat exercice.txt`

if [[ $progress -ge 0 ]] && [[ $progress -le 2 ]]
then
    sh raclette-exam 00
elif [[ $progress -ge 3 ]] && [[ $progress -le 5 ]]
then
    sh examplay 01
elif [[ $progress -ge 6 ]] && [[ $progress -le 8 ]]
then
    sh examplay 02
elif [[ $progress -ge 9 ]] && [[ $progress -le 11 ]]
then
    sh examplay 03
elif [[ $progress -ge 12 ]] && [[ $progress -le 14 ]]
then
    sh examplay 04
elif [[ $progress -ge 15 ]] && [[ $progress -le 17 ]]
then
    sh examplay 05
fi




