#!/bin/sh
progress=`cat progress.txt`

echo "Eval in progress"
#exercice=`cat exercice.txt`

./spawn.pl rendu "config/exam/00.pl"
echo "level is : $1"
#clear
./tools/build.sh
#clear

#echo "\n\n$(date) : \n" >> TRACE_$1.txt
#echo "+-+-+-+-+-+-+-+-+-+-+" >> TRACE_$1.txt
#echo "|N|o|r|m|i|n|e|t|t|e|" >> TRACE_$1.txt
#echo "+-+-+-+-+-+-+-+-+-+-+\n" >> TRACE_$1.txt

#./tools/verify.sh >> TRACE_$1.log

echo "\n+-+-+-+-+-+-+-+-+-+-+" > TRACE_$1.log
echo "|M|o|u|l|i|n|e|t|t|e|" >> TRACE_$1.log
echo "+-+-+-+-+-+-+-+-+-+-+\n" >> TRACE_$1.log

./tools/check_all.sh >> TRACE_$1.log

result=`grep -c 'good!' TRACE_$1.log` 

if grep -q ERROR TRACE_$1.log; then
    echo Error
else
    echo Good
    let progress=progress+1
    echo  $result > result.txt
    echo "$progress" > progress.txt
fi

rm -rf tools/ work/

#cp TRACE_$1.txt ~/Desktop

echo "The results can be found in TRACE_$1.log"
open ./TRACE_$1.log
